### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by Arkar-Aung** [wasabeef/glide-transformations#10] opened 2015-04-24 08:26 UTC
I have a button to apply transformation to my imageVew. I only got that error when apply ColorFilterTransformation and GrayscaleTransformation for the first time. But for the next time (restarting from 0), there is no problem. 

``` java
        switch (filterSwitchCount) {
            case 0 :
                transformation = new ContrastFilterTransformation(this, pool, 2.0f);
                break;
            case 1 :
                transformation = new ColorFilterTransformation(pool,
                        getResources().getColor(R.color.alpha_indigo));
                break;
            case 2 :
                transformation = new ToonFilterTransformation(this, pool);
                break;
            case 3 :
                transformation = new GrayscaleTransformation(pool);
                break;
        }

        if (++filterSwitchCount > 3) {
            filterSwitchCount = 0;
        }

        bitmap = Glide.with(this)
                           .load(imagePath)
                           .asBitmap()
                           .transform(transformation)
                           .into(100, 100)
                           .get();
        imageView.setImageBitmap(bitmap);
```

**Comment by wasabeef** [comment] 2015-04-24 08:52
@Arkar-Aung 
Hi

What Version?

**Comment by Arkar-Aung** [comment] 2015-04-24 09:02
@wasabeef  Library version is 1.0.6. Android version on device is 4.2.2.

**Comment by wasabeef** [comment] 2015-04-24 09:47
@Arkar-Aung 

OK.
I will investigate the cause.

**Comment by Arkar-Aung** [comment] 2015-04-24 09:55
@wasabeef I figure out that the problem is ContrastFilterTransformation and ToonFilterTransformation because the error occur after that transformations applied.

**Comment by wasabeef** [comment] 2015-04-24 10:08
Maybe GPUImage for Android might cause.

**Comment by Arkar-Aung** [comment] 2015-04-24 10:20
I've tested that it is okay after I remove ```source.recycle(); ``` . But I am not sure about memory matter. Check [this](http://stackoverflow.com/questions/3032497/android-trying-to-use-recycled-bitmap-error) .

**Comment by Razmaklat** [comment] 2015-11-09 07:45
Hi, I see that this issue is still open and I have had a similar issue. The problem was indeed resolved by removing `source.reccycle();`.

**Comment by lukesleeman** [comment] 2015-12-02 01:38
I was also getting similar errors - in my case it seems to be caused by source.recycle() in `BrightnessFilterTransformation.transform()` .  I have removed that line and everything is ok.

The weird thing is, the problem is intermittent - I would only get the errors showing up occasionally.

**Comment by TWiStErRob** [comment] 2016-03-08 18:11
@wasabeef there shouldn't be any `.recycle()` calls on Bitmaps that you received from Glide (except the ones explicitly requested from the pool, but in that case don't put it back in the pool), see `Transformation.transform` javadoc:

> Note - If the original resource object is not returned, the original resource will be recycled and it's internal resources may be reused. This means it is not safe to rely on the original resource or any internal state of the original resource in any new resource that is created. Usually this shouldn't occur, but if absolutely necessary either the original resource object can be returned with modified internal state, or the data in the original resource can be copied into the transformed resource.

And for even more related stuff see `BitmapTransformation.transform`

**Comment by timusus** [comment] 2016-11-04 12:01
I can't actually see any bitmap.recycle() calls anywhere in this library..

**Comment by TWiStErRob** [comment] 2016-11-04 12:50
@timusus where should it be recycling and why? The resources given to the transformations are automatically recycled (javadoc above). The returned resource cannot be recycled, because they will be in use a few moments later; they're recycled when Glide's target is cleared.

**Comment by timusus** [comment] 2016-11-04 12:54
I'm just saying that this library doesn't call `bitmap.recycle()` anywhere, in response to:
>...there shouldn't be any .recycle() calls on Bitmaps that you received from Glide 

As well as a bunch of comments above that say 'removing source.recycle() fixed the problem. 

If this library used to call `bitmap.recycle()`, it doesn't anymore. So, maybe this issue can be closed?

**Comment by TWiStErRob** [comment] 2016-11-04 13:04
Ah, yes, true that. It looks like it was removed in https://github.com/wasabeef/glide-transformations/commit/4a268b6dbdf9ecb9a3bd27601ea3b3a7ae08c56d; it's possible I was looking at an older version of the lib when I wrote that comment.

**Closed** 2018-01-30 02:44 UTC
